# Generated by Django 5.2.5 on 2025-08-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arvore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=150)),
                ('nome_cientifico', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
