# Generated by Django 5.2.5 on 2025-08-18 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo_mapa', models.CharField(choices=[('CARTOGRAFICO', 'Cartográfico'), ('CALOR', 'Mapa de Calor'), ('SATELITE', 'Satélite'), ('USO_SOLO', 'Uso de Solo'), ('EM_BRANCO', 'Em Branco')], default='CARTOGRAFICO', max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='projetos_colaborados', to=settings.AUTH_USER_MODEL)),
                ('editores', models.ManyToManyField(blank=True, related_name='projetos_editados', to=settings.AUTH_USER_MODEL)),
                ('visualizadores', models.ManyToManyField(blank=True, related_name='projetos_visualizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
