# Generated by Django 5.2.5 on 2025-08-18 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada'), ('ENCOSTA', 'Encosta'), ('FLORESTA', 'Floresta'), ('CANTEIRO', 'Canteiro')], max_length=50)),
                ('status', models.CharField(choices=[('PLANEJANDO', 'Planejando'), ('AGUARDANDO_APROVAÇAO', 'Aguardando Aprovação'), ('EM_EXECUCAO', 'Em Execução'), ('FINALIZADO', 'Finalizado'), ('JA_EXISTENTE', 'Já Existente')], max_length=50)),
                ('tipo_vegetacao', models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('NATIVA', 'Nativa'), ('EXOTICA', 'Exótica'), ('FRUTIFERA', 'Frutífera'), ('ORNAMENTAL', 'Ornamental'), ('MISTA', 'Mista')], max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('especies', models.ManyToManyField(blank=True, to='core.arvore')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='core.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
