# Generated by Django 5.2.5 on 2025-08-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='arvore',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arvore',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
