# Generated by Django 5.2.5 on 2025-08-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_arvore_latitude_arvore_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado')], default='EM_ABERTO', max_length=20),
        ),
    ]
