# Generated by Django 5.2.5 on 2025-08-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solicitacao_latitude_solicitacao_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='geom',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
