# Generated by Django 5.2.5 on 2025-08-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_area_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='solicitacoes/'),
        ),
    ]
