# Generated by Django 5.2.5 on 2025-08-27 23:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_equipe_membros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=150, unique=True)),
                ('nome_cientifico', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaArvore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('estado_saude', models.CharField(blank=True, choices=[('BOA', 'Boa'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('MORTA', 'Morta')], default='BOA', max_length=10, null=True)),
                ('data_plantio', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='core.especie')),
            ],
        ),
        migrations.DeleteModel(
            name='Arvore',
        ),
        migrations.AlterField(
            model_name='area',
            name='especies',
            field=models.ManyToManyField(blank=True, to='core.especie'),
        ),
    ]
