# Generated by Django 5.2.5 on 2025-09-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_especie_instanciaarvore_delete_arvore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('RECUSADO', 'Recusado')], default='EM_ABERTO', max_length=20),
        ),
    ]
