# Generated by Django 5.2.5 on 2025-09-03 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_solicitacao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='imagem',
        ),
        migrations.CreateModel(
            name='ImagemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='solicitacoes/')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.solicitacao')),
            ],
        ),
    ]
