# Generated by Django 5.2.5 on 2025-09-13 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_solicitacao_imagem_imagemsolicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Nativa, Frutífera, Ornamental', max_length=50, unique=True)),
                ('cor_fundo', models.CharField(default='#E9ECEF', help_text='Cor de fundo da tag (formato HEX, ex: #E9ECEF)', max_length=7)),
                ('cor_texto', models.CharField(default='#495057', help_text='Cor do texto da tag (formato HEX, ex: #495057)', max_length=7)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['categoria__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Tag',
                'verbose_name_plural': 'Categorias de Tags',
            },
        ),
        migrations.AddField(
            model_name='especie',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Foto que aparecerá no card do catálogo.', null=True, upload_to='especies_fotos/'),
        ),
        migrations.AddField(
            model_name='especie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='especies', to='core.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.tagcategory'),
        ),
    ]
