# Generated by Django 5.2.5 on 2025-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_popular_dados_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciaarvore',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
