# Generated by Django 5.2.5 on 2025-10-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_instanciaarvore_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CidadePermitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Cidade Permitida',
                'verbose_name_plural': 'Cidades Permitidas',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_residentes', to='core.cidadepermitida'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidades_secundarias',
            field=models.ManyToManyField(blank=True, related_name='usuarios_visitantes', to='core.cidadepermitida'),
        ),
    ]
