# Generated by Django 5.2.5 on 2025-10-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_cidadepermitida_profile_cidade_principal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cidadepermitida",
            name="geom",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
