# Generated by Django 5.2.5 on 2025-10-08 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_cidadepermitida_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="cidade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitacoes",
                to="core.cidadepermitida",
            ),
        ),
    ]
