# Generated by Django 5.2.5 on 2025-10-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_solicitacao_cidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="data_finalizacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
