# Generated by Django 5.2.5 on 2025-11-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_solicitacao_data_finalizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("PLANTIO", "Plantio de Muda"),
                    ("JARDINAGEM", "Manutenção de Jardim/Canteiro"),
                    ("EDUCACAO", "Ação Educativa"),
                    ("RISCO_QUEDA", "Risco de Queda"),
                    ("PODA_IRREGULAR", "Poda Drástica/Irregular"),
                    ("CORTE_ILEGAL", "Corte Ilegal"),
                    ("PRAGAS", "Pragas ou Doenças"),
                    ("MAUS_TRATOS", "Maus Tratos/Danos à Árvore"),
                    ("OUTRO", "Outro"),
                ],
                max_length=30,
                null=True,
                verbose_name="Categoria Detalhada",
            ),
        ),
    ]
