# Generated by Django 5.2.5 on 2025-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_solicitacao_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="motivo_recusa",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo da Recusa"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("PLANTIO", "Plantio de Muda"),
                    ("TROCA_LOCAL", "Troca de Local"),
                    ("JARDINAGEM", "Manutenção de Jardim/Canteiro"),
                    ("EDUCACAO", "Ação Educativa"),
                    ("RISCO_QUEDA", "Risco de Queda"),
                    ("PODA_IRREGULAR", "Poda Drástica/Irregular"),
                    ("CORTE_ILEGAL", "Corte Ilegal"),
                    ("PRAGAS", "Pragas ou Doenças"),
                    ("MAUS_TRATOS", "Maus Tratos/Danos à Árvore"),
                    ("OUTRO", "Outro"),
                ],
                max_length=30,
                null=True,
                verbose_name="Categoria Detalhada",
            ),
        ),
    ]
