# Generated by Django 5.2.5 on 2025-11-11 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_solicitacao_motivo_recusa_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="interessados",
            field=models.ManyToManyField(
                blank=True,
                related_name="solicitacoes_interesse",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuários Interessados",
            ),
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("lida", models.BooleanField(default=False)),
                (
                    "solicitacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.solicitacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
