# Generated by Django 5.2.5 on 2025-11-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_solicitacao_interessados_notificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ver_todas_solicitacoes",
            field=models.BooleanField(
                default=False, verbose_name="Ver solicitações da comunidade"
            ),
        ),
    ]
