# Generated by Django 5.2.5 on 2025-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_profile_ver_todas_solicitacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ver_todas_solicitacoes",
            field=models.BooleanField(
                default=True, verbose_name="Ver solicitações da comunidade"
            ),
        ),
    ]
