# Generated by Django 5.2.5 on 2025-11-29 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_profile_ver_todas_solicitacoes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="resolvido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_resolvidas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Staff Responsável",
            ),
        ),
    ]
