"""
Django settings for arbor_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tc%*k$22j0q2*3%g2jlk)8-!r2keb9n&j!&__^xzw5is#%$i!5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.loca.lt', '.app.github.dev']
CSRF_TRUSTED_ORIGINS = [
    'https://*.loca.lt',
    'https://*.ws.loca.lt', 'https://*.github.dev', 'https://humble-engine-5gvgx9j7wqwg3jg5-8000.app.github.dev/', 'https://*.github.dev','https://*.githubpreview.dev'
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Apps de terceiros
    'widget_tweaks',
    'django.contrib.sites', # <--- O allauth precisa disso

    # Apps do allauth (nosso kit de login social)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Módulo do Google
    'allauth.socialaccount.providers.apple',  # Módulo da Apple

    # Suas apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'arbor_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notificacoes_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'arbor_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', 
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'core/static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'

LOGIN_URL = 'login'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGOUT_REDIRECT_URL = 'login'

AUTHENTICATION_BACKENDS = [
    # Usado para logar no admin com username e senha
    'django.contrib.auth.backends.ModelBackend',

    # Lógica de autenticação do allauth (email, social, etc.)
    'allauth.account.auth_backends.AuthenticationBackend',
]
# ID do site. O allauth usa isso pra gerenciar múltiplos sites se precisar.
# Pra gente, 1 é o padrão e tá de boa.
SITE_ID = 1

# --- Configurações de conta do allauth ---
ACCOUNT_AUTHENTICATION_METHOD = 'email'   # Define que o login será feito via e-mail
ACCOUNT_EMAIL_REQUIRED = True           # Exige que todo usuário tenha um e-mail
ACCOUNT_USERNAME_REQUIRED = False       # Torna o campo 'username' opcional
ACCOUNT_SIGNUP_FIELDS = ['email', 'username', 'password1'] # CORRIGIDO: usa 'password1'
ACCOUNT_SESSION_REMEMBER = True         # Permite que o usuário continue logado
ACCOUNT_EMAIL_VERIFICATION = 'optional' # Não força a verificação de e-mail no começo